#!/bin/bash

formatter="git-clang-format"

if ( test -e ${formatter} ); then
	echo "unable to find formatter ($formatter)"
	exit 1
fi

$formatter --diff | grep "no modified files to format" && exit 0
$formatter --diff | grep "clang-format did not modify any files" && exit 0

$formatter -f
echo -e "\e[95mclang-format: \e[93m\e[5msome files has been changed\e[0m\n"
exit 1
